### ISSUE TITLE
Compile help

### ISSUE THREAD

**Issue by daci5455** [5trange/ClamGuard#2]
Hi how can this project be compiled I'm looking to add more features

**Comment by Itsr1ght** [comment]
We're using Python to run this project. Are you asking about how we compile the python script to windows executable or the compilation of installation executable? @daci5455

**Comment by daci5455** [comment]
I'm asking for compilation fo installation executable

**Comment by 5trange** [comment]
The first step of this involves packaging the python source files into actual windows executables that doesn't require a local Python install. We're using py2exe for this. As for the compilation of the installation file, we're using Inno setup to do that. You can see the Inno setup script under /install/
